---
name: Docs QA

on:
  pull_request_target:
    paths:
      - "**"

permissions:
  pull-requests: write

jobs:
  documentation-preview:
    runs-on: ubuntu-latest
    steps:
      - uses: readthedocs/actions/preview@v1
        with:
          project-slug: "datacube-explorer"
          message-template: |
            ---
            :books:
            ðŸ“š Global Documentation preview test ðŸ“š: {docs-pr-index-url}
